from htd_validate.validators.td import TreeDecompositionValidator
from htd_validate.validators.ghtd import GeneralizedHypertreeDecompositionValidator
from htd_validate.validators.htd import HypertreeDecompositionValidator
from htd_validate.validators.fhtd import FractionalHypertreeDecompositionValidator
#from auto import AutoDecompositionValidator
